
import Image from "next/image";
import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import { ArrowRight, Check, Mail, MapPin, Menu, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
const links=[["Home","/"],["Services","/services"],["How It Works","/how-it-works"],["About","/about"],["Contact","/contact"]] as const;
export function PublicHeader(){return <header className="public-header"><div className="public-wrap public-nav"><Link className="public-brand" href="/" aria-label="CyberShield home"><Image src="/cybershield-logo.png" alt="CyberShield" width={205} height={54} priority/></Link><nav className="public-desktop-nav" aria-label="Primary">{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link className="nav-cta" href="/contact">Get in touch</Link></nav><details className="public-mobile-nav"><summary><Menu aria-hidden size={22}/><span className="sr-only">Open menu</span></summary><nav aria-label="Mobile">{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav></details></div></header>}
export function PublicFooter(){return <footer className="public-footer"><div className="public-wrap footer-main"><div className="footer-intro"><Image src="/cybershield-logo.png" alt="CyberShield" width={190} height={50}/><p>Practical cybersecurity support for Australian homes and businesses, explained in plain English.</p></div><div><h2>Explore</h2><Link href="/services">Services</Link><Link href="/how-it-works">How It Works</Link><Link href="/about">About Us</Link><Link href="/contact">Contact</Link></div><div><h2>Contact</h2><a href="mailto:info@cybershieldau.com.au"><Mail size={16}/>info@cybershieldau.com.au</a><p><MapPin size={16}/>121 Collins St<br/>Melbourne VIC 3000</p><small>10 AMâ€“9 PM AEST</small></div><div><h2>Legal</h2><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Website Terms</Link><Link href="/service-terms">Service Terms</Link></div></div><div className="public-wrap footer-bottom"><span>Â© {new Date().getFullYear()} CyberShield Australia</span><span>Reference AU 6927809</span></div></footer>}
export function SiteShell({children}:{children:ReactNode}){return <><a className="skip-link" href="#main">Skip to content</a><PublicHeader/><main id="main">{children}</main><PublicFooter/></>}
export function Breadcrumbs({items}:{items:readonly (readonly [string,string])[]}){return <nav className="public-wrap breadcrumbs" aria-label="Breadcrumb">{items.map(([label,href],i)=><span key={`${href}-${label}`}>{i>0&&<b>/</b>}<Link href={href}>{label}</Link></span>)}</nav>}
export function PageHero({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children?:ReactNode}){return <section className="page-hero"><div className="public-wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-copy">{copy}</p>{children}</div></section>}
export function SectionHeading({eyebrow,title,copy,align="left"}:{eyebrow:string;title:string;copy?:string;align?:"left"|"center"}){return <div className={`section-heading ${align}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function FeatureCard({icon:Icon,title,children}:{icon:LucideIcon;title:string;children:ReactNode}){return <article className="feature-card"><span className="icon-box"><Icon size={22}/></span><h3>{title}</h3><div>{children}</div></article>}
export function ServiceCard({icon:Icon,title,description,items,href,forWhom}:{icon:LucideIcon;title:string;description:string;items:string[];href:string;forWhom?:string}){return <article className="service-card-premium"><span className="icon-box"><Icon size={24}/></span><h3>{title}</h3>{forWhom&&<p className="for-whom">Best suited to: {forWhom}</p>}<p>{description}</p><ul className="check-list">{items.map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul><Link className="text-link" href={href}>Explore {title}<ArrowRight size={16}/></Link></article>}
export function ProcessSteps({steps}:{steps:{title:string;body:string}[]}){return <ol className="process-grid">{steps.map((step,index)=><li key={step.title}><span>{String(index+1).padStart(2,"0")}</span><h3>{step.title}</h3><p>{step.body}</p></li>)}</ol>}
export function TrustSection(){return <section className="public-section trust-section"><div className="public-wrap split-layout"><div><SectionHeading eyebrow="A responsible approach" title="Clear support, documented properly" copy="CyberShield focuses on practical help and clear expectationsâ€”not fear, inflated promises or technical theatre."/><Link className="button-secondary" href="/about">About CyberShield<ArrowRight size={17}/></Link></div><div className="trust-points">{["Plain-English communication","Service scope recorded for each customer","Secure confirmation and agreement process","Transparent limitations and customer responsibilities"].map(item=><div key={item}><ShieldCheck size={20}/><span>{item}</span></div>)}</div></div></section>}
export function CTASection({title="Talk through your cybersecurity concern",copy="Tell us what has happened and what you need help with. Weâ€™ll respond with practical next steps."}:{title?:string;copy?:string}){return <section className="cta-section"><div className="public-wrap cta-inner"><div><p className="eyebrow">Start a conversation</p><h2>{title}</h2><p>{copy}</p></div><Link className="button-primary" href="/contact">Contact CyberShield<ArrowRight size={17}/></Link></div></section>}
export function ContactPanel(){return <aside className="contact-panel"><p className="eyebrow">Contact details</p><h2>CyberShield Australia</h2><a href="mailto:info@cybershieldau.com.au"><Mail size={19}/>info@cybershieldau.com.au</a><p><MapPin size={19}/><span>121 Collins St<br/>Melbourne VIC 3000</span></p><div className="contact-note"><strong>Support hours</strong><span>10 AMâ€“9 PM AEST</span></div><small>Please do not send passwords, recovery codes, identity documents or payment-card details.</small></aside>}
export function FAQAccordion({items}:{items:{question:string;answer:string}[]}){return <div className="faq-accordion">{items.map(item=><details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</div>}
