import type { Metadata } from "next";
import { PageHero, SiteShell } from "@/components/public/SiteShell";
import { publicMetadata } from "@/lib/public-metadata";
import { contactAction } from "./actions";
export const metadata: Metadata = publicMetadata("Contact", "Contact CyberShield Australia about Network Security or Identity & IP Protector services.", "/contact");
export default async function ContactPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status } = await searchParams;
  return <SiteShell><PageHero eyebrow="Contact" title="Start a clear security conversation." copy="Tell us what you need help protecting. A CyberShield team member will respond with practical next steps." /><section className="public-section"><div className="public-container public-split"><div><h2>How can we help?</h2><p>Email: info@cybershieldau.com.au</p><p>Do not submit passwords, recovery codes, identity documents, payment-card details, or other highly sensitive information.</p></div><form action={contactAction} className="public-form"><input name="website" tabIndex={-1} autoComplete="off" className="honeypot" aria-hidden="true" /><label>Name<input name="name" required maxLength={100} /></label><label>Email<input name="email" type="email" required maxLength={254} /></label><label>Phone (optional)<input name="phone" maxLength={30} /></label><label>Topic<select name="topic" required><option>General Enquiry</option><option>Network Security</option><option>Identity &amp; IP Protector</option><option>Existing Customer Support</option><option>Billing</option><option>Agreement or Documentation</option></select></label><label>Message<textarea name="message" required minLength={10} maxLength={4000} rows={7} /></label><label className="checkbox"><input name="consent" type="checkbox" required /> I consent to CyberShield using these details to respond to my enquiry.</label><button className="public-primary" type="submit">Send enquiry</button>{status === "received" && <p className="success-message" role="status">Thank you. Your enquiry has been received.</p>}{status === "invalid" && <p className="error-message" role="alert">Please check the form and try again.</p>}</form></div></section></SiteShell>;
}
