import Link from "next/link";
import { Prisma } from "@prisma/client";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { InternalShell } from "@/components/internal/InternalShell";
import { adminLogoutAction } from "./login/actions";

type Params = { q?: string; from?: string; to?: string };
export default async function AdminPage({ searchParams }: { searchParams: Promise<Params> }) {
  await requireAdmin(); const params = await searchParams; const q = params.q?.trim() || "";
  const dateWhere = params.from || params.to ? { saleDate: { ...(params.from ? { gte: new Date(`${params.from}T00:00:00Z`) } : {}), ...(params.to ? { lte: new Date(`${params.to}T00:00:00Z`) } : {}) } } : {};
  const where: Prisma.CustomerWhereInput = q ? { OR: [{ customerId: { contains: q, mode: "insensitive" } }, { name: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }, { phone: { contains: q } }, { alternatePhone: { contains: q } }, { address: { contains: q, mode: "insensitive" } }, { createdByAgentName: { contains: q, mode: "insensitive" } }, { lastActionAgentName: { contains: q, mode: "insensitive" } }, { purchases: { some: { OR: [{ primaryIssue: { contains: q, mode: "insensitive" } }, { serviceDetails: { contains: q, mode: "insensitive" } }, { agentName: { contains: q, mode: "insensitive" } }] } } }] } : {};
  const [customers, totals, failedSends, audits] = await Promise.all([
    prisma.customer.findMany({ where, include: { purchases: { orderBy: { createdAt: "desc" }, take: 1 }, agreements: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: 200 }),
    prisma.purchase.groupBy({ by: ["currency"], where: dateWhere, _sum: { salesAmount: true }, _count: true }),
    prisma.confirmationSend.count({ where: { status: "FAILED" } }), prisma.adminAuditEvent.findMany({ orderBy: { timestamp: "desc" }, take: 20 }),
  ]);
  return <InternalShell role="Administrator" logoutAction={adminLogoutAction}><p className="internal-eyebrow">Owner operations</p><h1>Customer administration</h1><p className="internal-lead">Search complete customer and service records, review totals by currency, delivery failures and recent audited actions.</p>
    <section className="internal-card" style={{ padding: "1.5rem" }}><form className="internal-form-grid"><label>Search all customer and service fields<input name="q" defaultValue={q} /></label><label>Sale date from<input name="from" type="date" defaultValue={params.from} /></label><label>Sale date to<input name="to" type="date" defaultValue={params.to} /></label><button className="internal-primary" type="submit">Run report</button></form><div className="summary-grid">{totals.map((item) => <span key={item.currency}>{item.currency} sales ({item._count})<strong>{item.currency} {item._sum.salesAmount?.toFixed(2) ?? "0.00"}</strong></span>)}<span>Failed confirmation sends<strong>{failedSends}</strong></span><span>Matching customers<strong>{customers.length}</strong></span></div></section>
    <section className="internal-card" style={{ marginTop: "1.25rem" }}><div className="internal-section-heading"><h2>Customer records</h2><span>Up to 200 results</span></div><div className="internal-table-wrap"><table className="internal-table"><thead><tr><th>Customer</th><th>Contact</th><th>Latest sale</th><th>Agreement</th><th>Agents</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><Link href={`/admin/customers/${customer.id}`}>{customer.customerId}</Link><span>{customer.name}</span></td><td>{customer.email}<span>{customer.phone || "No phone"}</span></td><td>{customer.purchases[0] ? `${customer.purchases[0].currency} ${customer.purchases[0].salesAmount.toFixed(2)}` : "None"}<span>{customer.purchases[0]?.saleDate.toISOString().slice(0, 10)}</span></td><td><span className={`status-chip ${(customer.agreements[0]?.status || "draft").toLowerCase()}`}>{customer…8402 tokens truncated…3,.1);color:#fca5a5!important}
.table-actions{display:flex;flex-wrap:wrap;align-items:center;gap:.7rem}.link-button{border:0;background:none;padding:0;color:#8ec5ff;font:inherit;font-weight:700;cursor:pointer}.link-button.internal-danger{color:#fca5a5}.summary-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.75rem;margin-top:1.2rem}.summary-grid span{border:1px solid rgba(255,255,255,.08);border-radius:.7rem;padding:.75rem;color:#718096;font-size:.68rem}.summary-grid strong{display:block;margin-top:.3rem;color:white;font-size:.82rem}
.agreement-preview{border:1px solid rgba(255,255,255,.1);border-radius:.8rem;background:#020914;overflow:hidden}.agreement-preview summary{cursor:pointer;padding:.85rem 1rem;color:#dce6f4;font-size:.78rem;font-weight:700}.agreement-preview pre{max-height:580px;overflow:auto;margin:0;border-top:1px solid rgba(255,255,255,.08);padding:1.2rem;white-space:pre-wrap;color:#aebbd0;font:12px/1.75 Arial,sans-serif}.audit-list{margin-top:1rem;border-left:1px solid rgba(82,214,255,.22);padding-left:1.2rem}.audit-list li{display:flex;flex-direction:column;margin:.8rem 0}.audit-list strong{color:#dce6f4;font-size:.75rem}.audit-list span{margin-top:.2rem;color:#718096;font-size:.68rem}

.sign-root{min-height:100vh;background:radial-gradient(circle at 85% 0,rgba(47,125,255,.16),transparent 32%),#020712;padding:26px 12px 70px;color:#e8eef9}.sign-shell{width:min(900px,100%);margin:0 auto}.sign-brand{display:flex;align-items:center;justify-content:space-between;padding:12px 0 26px}.sign-brand img{height:50px;width:auto;max-width:210px;object-fit:contain}.sign-brand div{display:flex;flex-direction:column;text-align:right}.sign-brand span,.sign-brand small{color:#718096;font-size:.68rem}.sign-brand strong{margin-top:.25rem;color:white;font-size:.8rem}
.sign-hero{border:1px solid rgba(255,255,255,.1);border-bottom:0;border-radius:1.4rem 1.4rem 0 0;background:linear-gradient(135deg,rgba(47,125,255,.17),rgba(255,255,255,.03));padding:clamp(1.5rem,5vw,3.4rem)}.sign-hero p{color:#52d6ff;font-size:.68rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.sign-hero h1{margin:.65rem 0;font-size:clamp(2rem,6vw,3.5rem);font-weight:600;letter-spacing:-.04em;color:white}.sign-hero span{color:#9facbf;font-size:.82rem}
.sign-summary{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.035)}.sign-summary div{min-height:105px;border-right:1px solid rgba(255,255,255,.08);padding:1.15rem}.sign-summary div:last-child{border-right:0}.sign-summary span{display:block;color:#718096;font-size:.64rem;text-transform:uppercase;letter-spacing:.08em}.sign-summary strong{display:block;margin-top:.65rem;color:white;font-size:.83rem}.sign-summary small{display:block;margin-top:.25rem;color:#8190a6;font-size:.68rem;overflow-wrap:anywhere}
.sign-document,.sign-form{margin-top:1.25rem;border:1px solid rgba(255,255,255,.1);border-radius:1.2rem;background:#07101f;padding:clamp(1.2rem,4vw,2.2rem)}.sign-document-heading{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1.3rem}.sign-document-heading span{color:#52d6ff;font-size:.65rem;text-transform:uppercase;letter-spacing:.09em}.sign-document-heading h2,.sign-form h2{margin-top:.25rem;color:white;font-size:1.3rem;font-weight:650}.sign-document-heading a{border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:.65rem .9rem;color:#dce6f4;font-size:.7rem;font-weight:700}.sign-document pre{max-height:720px;overflow:auto;border-radius:.8rem;background:white;padding:clamp(1rem,4vw,2rem);white-space:pre-wrap;color:#252b33;font:12px/1.75 Arial,sans-serif}
.sign-form>p{margin:.5rem 0 1.2rem;color:#8f9eb2;font-size:.8rem;line-height:1.6}.sign-form>label:not(.consent-row){display:block;margin:.9rem 0 .45rem;color:#cbd5e1;font-size:.75rem;font-weight:700}.sign-form>input{width:100%;border:1px solid rgba(255,255,255,.13);border-radius:.7rem;background:#020914;padding:.85rem 1rem;color:white}.signature-label{display:flex;align-items:center;justify-content:space-between;margin:1.3rem 0 .55rem;color:#cbd5e1;font-size:.75rem;font-weight:700}.signature-label button{border:0;background:none;color:#8ec5ff;font-size:.72rem;cursor:pointer}.signature-canvas{display:block;width:100%;height:220px;border:2px dashed #aab4c3;border-radius:.75rem;background:white;touch-action:none}.consent-row{display:flex!important;align-items:flex-start;gap:.85rem;margin:1.3rem 0;color:#bcc7d6!important;font-size:.78rem!important;line-height:1.65}.consent-row input{width:18px;height:18px;flex:0 0 auto;margin-top:.18rem;accent-color:#2f7dff}.sign-submit{width:100%;min-height:52px;border:0;border-radius:999px;background:#2f7dff;color:white;font-weight:800;cursor:pointer}.sign-submit:disabled{opacity:.6;cursor:wait}.sign-final-note{text-align:center;font-size:.7rem!important}.sign-alert{margin:1rem 0;border-radius:.7rem;padding:.85rem;font-size:.78rem}
.sign-footer{display:flex;flex-direction:column;align-items:center;gap:.35rem;padding:2rem;text-align:center}.sign-footer strong{color:white;font-size:.8rem}.sign-footer span{color:#8a99ae;font-size:.7rem}.sign-footer small{margin-top:.5rem;color:#5f6e83;font-size:.65rem}.sign-error-card,.sign-complete{border:1px solid rgba(255,255,255,.1);border-radius:1.3rem;background:#07101f;padding:clamp(1.5rem,6vw,4rem);text-align:center}.sign-error-card h1,.sign-complete h1{font-size:clamp(2rem,6vw,3.4rem);font-weight:600;letter-spacing:-.04em;color:white}.sign-error-card p,.sign-complete>span{display:block;max-width:580px;margin:1rem auto;color:#93a4ba;line-height:1.7}.complete-check{display:grid;width:68px;height:68px;place-items:center;margin:0 auto 1.4rem;border-radius:50%;background:rgba(74,222,128,.12);color:#86efac;font-size:2rem}.sign-complete>p{color:#52d6ff;font-size:.68rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.sign-complete dl{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin:2rem 0}.sign-complete dl div{border:1px solid rgba(255,255,255,.08);border-radius:.7rem;padding:1rem}.sign-complete dt{color:#718096;font-size:.64rem;text-transform:uppercase}.sign-complete dd{margin:.4rem 0 0;color:white;font-size:.8rem}.sign-complete small{color:#718096;font-size:.7rem}
@media(max-width:800px){.internal-grid{grid-template-columns:1fr}.sign-summary{grid-template-columns:repeat(2,1fr)}.sign-summary div:nth-child(2){border-right:0}.sign-summary div:nth-child(-n+2){border-bottom:1px solid rgba(255,255,255,.08)}}
@media(max-width:600px){.internal-nav{align-items:flex-start;padding:14px 0}.internal-nav nav{flex-wrap:wrap;justify-content:flex-end;gap:.55rem .8rem}.internal-nav img{height:38px}.internal-content{padding-top:38px}.internal-form-grid,.summary-grid{grid-template-columns:1fr}.sign-document-heading{align-items:flex-start;flex-direction:column}.sign-complete dl{grid-template-columns:1fr}.sign-brand{align-items:flex-start}.sign-brand img{height:42px}.sign-summary{grid-template-columns:1fr}.sign-summary div{border-right:0!important;border-bottom:1px solid rgba(255,255,255,.08)}}


/* Multi-page public experience */
.site-wrap,.public-container{width:min(1180px,calc(100% - 40px));margin-inline:auto}.site-header{position:sticky;top:0;z-index:50;background:rgba(2,7,18,.92);border-bottom:1px solid rgba(255,255,255,.1);backdrop-filter:blur(16px)}.nav-row{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:24px}.desktop-nav{display:flex;align-items:center;gap:20px}.desktop-nav a,.mobile-nav a,.site-footer a{color:#cbd5e1;text-decoration:none;font-size:14px}.desktop-nav a:hover,.site-footer a:hover{color:#52d6ff}.mobile-nav{display:none}.page-hero{padding:96px 0 76px;background:radial-gradient(circle at 75% 15%,rgba(47,125,255,.22),transparent 35%),linear-gradient(180deg,#061229,#020712);border-bottom:1px solid rgba(255,255,255,.08)}.page-hero h1{max-width:900px;margin:.35rem 0 1rem;font-size:clamp(2.7rem,7vw,5.5rem);line-height:1;letter-spacing:-.055em}.page-hero>div>p:last-child{max-width:760px;color:#aebbd0;font-size:1.15rem;line-height:1.75}.kicker{color:#52d6ff;text-transform:uppercase;letter-spacing:.18em;font-weight:800;font-size:.75rem}.public-section{padding:88px 0}.public-section h2,.legal-copy h2{font-size:clamp(2rem,4vw,3.4rem);letter-spacing:-.035em}.public-section p,.legal-copy p{color:#aebbd0;line-height:1.8}.public-split{display:grid;grid-template-columns:1fr 1.1fr;gap:64px}.public-grid,.service-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.public-card,.service-card,.public-form{padding:30px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.045)}.public-card a,.service-card a{color:#52d6ff}.public-primary,.public-secondary{display:inline-flex;min-height:48px;align-items:center;justify-content:center;border-radius:999px;padding:12px 22px;font-weight:800;text-decoration:none}.public-primary{border:0;background:#2f7dff;color:#fff}.public-secondary{border:1px solid rgba(255,255,255,.2);color:#fff}.public-form{display:grid;gap:18px}.public-form label{display:grid;gap:8px;color:#dce6f6;font-weight:700}.public-form input,.public-form select,.public-form textarea{width:100%;border:1px solid rgba(255,255,255,.15);border-radius:10px;background:#071226;color:#fff;padding:13px;font:inherit}.public-form .checkbox{grid-template-columns:auto 1fr;font-weight:400}.public-form .checkbox input{width:auto}.honeypot{position:absolute!important;left:-9999px!important}.success-message{color:#76e4b2!important}.error-message{color:#ff9d9d!important}.legal-copy{padding-top:72px;padding-bottom:100px;max-width:850px}.legal-copy h2{font-size:1.7rem;margin-top:2.7rem}.breadcrumbs{padding:16px 0;color:#9aaac0}.site-footer{padding:62px 0;border-top:1px solid rgba(255,255,255,.1);background:#01040b}.footer-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:40px}.site-footer h2{font-size:1rem}.site-footer a{display:block;margin:10px 0}.site-footer p,.site-footer small{color:#94a3b8;line-height:1.7}
@media(max-width:900px){.desktop-nav{display:none}.mobile-nav{display:block;position:relative}.mobile-nav summary{cursor:pointer}.mobile-nav nav{position:absolute;right:0;top:35px;width:260px;padding:18px;display:grid;gap:14px;background:#071226;border:1px solid rgba(255,255,255,.15);border-radius:14px}.public-split,.public-grid,.service-grid,.footer-grid{grid-template-columns:1fr}.page-hero{padding:72px 0 55px}}
