import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { InternalShell } from "@/components/internal/InternalShell";
import { adminLogoutAction } from "../../login/actions";
import { addAdminNoteAction, updateCustomerAction } from "../../actions";

export default async function CustomerPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const session = await requireAdmin(); const { id } = await params; const messages = await searchParams;
  const customer = await prisma.customer.findUnique({ where: { id }, include: { purchases: { orderBy: { createdAt: "desc" }, include: { confirmationSends: { orderBy: { createdAt: "desc" } } } }, agreements: { orderBy: { createdAt: "desc" }, include: { sends: { orderBy: { createdAt: "desc" } }, events: { orderBy: { timestamp: "desc" } } } }, notes: { orderBy: { createdAt: "desc" } } } }); if (!customer) notFound();
  return <InternalShell role="Administrator" logoutAction={adminLogoutAction}><Link href="/admin">← Back to customers</Link><p className="internal-eyebrow" style={{ marginTop: "1.5rem" }}>Full customer record</p><h1>{customer.name}</h1><p className="internal-lead">{customer.customerId} · created {customer.createdAt.toISOString()}</p>{messages.success && <div className="internal-alert success">{messages.success}</div>}{messages.error && <div className="internal-alert error">{messages.error}</div>}
    <div className="internal-grid"><section className="internal-card" style={{ padding: "1.5rem" }}><h2>Customer details</h2><form action={updateCustomerAction} className="internal-form"><input type="hidden" name="customerId" value={customer.id} /><input type="hidden" name="csrfToken" value={session.csrfToken} /><div className="internal-form-grid"><label>First name<input name="firstName" defaultValue={customer.firstName} required /></label><label>Last name<input name="lastName" defaultValue={customer.lastName || ""} /></label></div><label>Email<input name="email" type="email" defaultValue={customer.email} required /></label><div className="internal-form-grid"><label>Phone<input name="phone" defaultValue={customer.phone || ""} /></label><label>Alternate phone<input name="alternatePhone" defaultValue={customer.alternatePhone || ""} /></label></div><label>Address<textarea name="address" defaultValue={customer.address} required rows={3} /></label><label>Administrator name<input name="agentName" required /></label><button className="internal-primary">Save correction</button></form></section>
    <section className="internal-card" style={{ padding: "1.5rem" }}><h2>Append-only internal notes</h2><form action={addAdminNoteAction} className="internal-form"><input type="hidden" name="customerId" value={customer.id} /><input type="hidden" name="csrfToken" value={session.csrfToken} /><label>Administrator name<input name="agentName" required /></label><label>Note<textarea name="noteText" required maxLength={4000} rows={4} /></label><button className="internal-secondary">Add note</button></form><ul className="audit-list">{customer.notes.map((note) => <li key={note.id}><strong>{note.agentName} · {note.source}</strong><span>{note.createdAt.toISOString()}</span><span>{note.noteText}</span></li>)}</ul></section></div>
    <section className="internal-card" style={{ marginTop: "1.25rem" }}><div className="internal-section-heading"><h2>Purchase and confirmation history</h2></div><div className="internal-table-wrap"><table className="internal-table"><thead><tr><th>Sale</th><th>Service</th><th>Delivery</th><th>Agents</th></tr></thead><tbody>{customer.purchases.map((purchase) => <tr key={purchase.id}><td>{purchase.currency} {purchase.salesAmount.toFixed(2)}<span>{purchase.saleDate.toISOString().slice(0, 10)}</span></td><td>{purchase.primaryIssue}<span>{purchase.serviceDetails}</span></td><td>{purchase.status}<span>{purchase.confirmationSends.map((send) => `${send.sendType}: ${send.status}${send.resendEmailId ? ` (${send.resendEmailId})` : ""}`).join(" · ") || "No attempts"}</span></td><td>{purchase.createdByAgentName}<span>Last: {purchase.lastActionAgentName}</span></td></tr>)}</tbody></table></div></section>
    <section className="internal-card" style={{ marginTop: "1.25rem" }}><div className="internal-section-heading"><h2>Agreement history</h2></div><div className="internal-table-wrap"><table className="internal-table"><thead><tr><th>Agreement</th><th>Status</th><th>Delivery</th><th>Signed document</th></tr></thead><tbody>{customer.agreements.map((agreement) => <tr key={agreement.id}><td>{agreement.agreementNumber}<span>v{agreement.agreementVersion}</span></td><td>{agreement.status}<span>{agreement.signedAt?.toISOString()}</span></td><td>{agreement.sends.map((send) => `${send.sendType}: ${send.status}`).join(" · ") || "No attempts"}</td><td>{agreement.signedPdfUrl ? <Link href={`/api/internal/agreements/${agreement.id}/download`}>Download signed PDF</Link> : "Not signed"}</td></tr>)}</tbody></table></div></section>
  </InternalShell>;
}
